name: Goat Farm Arts Center
favicon: null
layout_spectrum: 0.14580161683261395
typography_spectrum: 0.3132057769689709
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.1790596793871373
  lightness: 0.8064135930035263
  saturation: 0.6116985192056745
  rhythmicContrast: 0.7154433003161103
purpose: []
