name: Goat Farm Arts Center
favicon: null
layout_spectrum: 0.76182
typography_spectrum: 0.49738
title: 'Break the path, excite new thinking.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#536057'
    - '#344b43'
    - '#888f66'
    - '#c5a666'
    - '#986e4a'
  brandStrength: 0.375
  lightness: 0.8064135930035263
  saturation: 0
  rhythmicContrast: 0.7154433003161103
purpose: []
